Fix for Windows.
dylanmckay/vsprintf pull request #1
Opened 2020-06-23 21:55 UTC by daxpedda

I explained it in the comments as well as I could. Feel free to poke me with any questions.

2020-06-24 13:16 UTC, dylanmckay commented
This looks good  - I've left one comment on the comment but once that's sorted I'm happy to merge this.

I surprised myself that I never added any tests for this crate - it seems that is because it is hard to create a va_list pointer from pure Rust. I will have another go at adding a test for this.

2020-06-24 13:17 UTC, dylanmckay requested changes

2020-06-24 13:17 UTC, dylanmckay commented on src/lib.rs
> +    #[cfg(windows)]
Is there a reference/URL/citation that explains this difference on Windows that can be added to this comment?

2020-06-24 14:26 UTC, daxpedda commented on src/lib.rs
> +    #[cfg(windows)]
Sadly I don't. As far as I could gather from stackoverflow answers, the issue is the other way around.

C code:
```c
void set_logger(void (*logger_fun)(const char *message, va_list args));
```

Rust code:
```rust
extern "C" {
    fn set_logger(logger_func: Option<extern "C" fn(message: *const c_char, args: *mut c_void)>);
}
```

So for some reason this works on linux, I don't know why, because in C it clearly says `va_list args` but in Rust we write `args: *mut c_void`.
On stackoverflow I have read multiple times that on Linux `va_list` is really a pointer (like really, not **containing** a pointer, but **is** a pointer).
My first try was was to change `vsprintf` to just use [`VaList`](https://doc.rust-lang.org/std/ffi/struct.VaList.html) properly, instead of `*mut V`, which obviously is an issue, because it's not stable. Alternatively I tried using the [`va_list`](https://crates.io/crates/va_list) crate, which worked fine.

Now the Rust code looks like this:
```rust
extern "C" {
    fn set_logger(logger_func: Option<extern "C" fn(message: *const c_char, args: va_list::VaList)>);
}
```
Which made more sense to me.
This worked fine on Windows, but didn't work on Linux, I'm unsure why exactly.

2020-06-25 14:34 UTC, daxpedda commented on src/lib.rs
> +    #[cfg(windows)]
I had some today to play around with this a bit more.
To summarize what I belive was the issue, on Linux `va_copy` handled what was rly a double pointer, correctly, windows didn't.

2020-07-01 05:49 UTC, merged

2020-07-01 05:54 UTC, dylanmckay commented
Released version `1.0.3` - thanks for the patch @daxpedda